### ISSUE TITLE
grunt version 1.0.1 

### ISSUE THREAD

**Issue by novarine** [vlocityinc/vlocity_build#12]
with grunt version 1.0.1 the customized .properties file is not recognized.
`>> Vlocity Build Tools
>> Could not load properties file from true
>> No propertyfile selected. Please create a "build.properties" file following
>> the template provided in template.build.properties. Or specify a
>> -propertyfile.
Warning: Task "build_myorg.properties" not found. Use --force to continue.
`
not an issue with grunt 0.4.5 who's defined in package.json source

**Comment by rutlabaga** [comment]
This is due to a change in grunt 1.0 that now requires an = between options. So if anyone does experience this issue you can use the syntax:

grunt -propertyfile=build_myorg.properties -job=JobFile packExport

This syntax also works with the 0.4.5 version.

I am working to make sure I have the package.json setup to correctly enforce the versions defined there as this is a strangely non backwards compatible change in grunt.
