### ISSUE TITLE
FilterFields of OverrideSettings not working for Vlocity Objects

### ISSUE THREAD

**Issue by rajatshilwant** [vlocityinc/vlocity_build#174]
[Vlocity Build Tool Issue.zip](https://github.com/vlocityinc/vlocity_build/files/2875584/Vlocity.Build.Tool.Issue.zip)
Hi Team,
In my Job file while exporting data from one of our developers environment, I have tried to filter out one of the custom fields Load_ID__c present on the vocity as well as Salesforce objects using OverrideSettings FilterFields as per the documentation provided. It seems to be working for SObjects like Product2, Pricebook2, PricebookEntry but is not working for Vlocity objects like Rules, Calculation Matrices, Calculation Procedures,etc.
I need your help with getting the export out without this field.
 Also I have attached the job file for your reference.

**Comment by rutlabaga** [comment]
Sorry for the late response. The syntax is actually just with `vlocity_namespace__ItemImplementation__c` instead of `vlocity_cmt__ItemImplementation__c`. But this may be a hassle to add to all your objects. It may be easier to change the Field Level Visibility for the user doing the export to remove this field.
