### ISSUE TITLE
Attribute Assignments duplicated after renaming attribute

### ISSUE THREAD

**Issue by muminekimalami** [vlocityinc/vlocity_build#78]
After changing code of the attribute, exporting and deploying data we have duplicated Global Keys in vlocity_cmt__AttributeAssignment__c table:
![image](https://user-images.githubusercontent.com/36472902/43198810-33b4bd84-9010-11e8-9e50-62407721c787.png)

**Comment by rutlabaga** [comment]
For AttributeAssignments the default Matching Key is the `%vlocity_namespace%__ObjectId__c, %vlocity_namespace%__AttributeId__c, %vlocity_namespace%__IsOverride__c` fields. 

You must create a new Matching Key as the GlobalKey in order to make the GlobalKey the active Matching Field.

https://github.com/vlocityinc/vlocity_build#creating-custom-matching-keys

If you have already done this, then these duplicates were not caused by the build tool, and so they may need to be fixed manually.
