### ISSUE TITLE
Unable to Deploy Calculation Matrix using Latest Vlocity Build and Node JS

### ISSUE THREAD

**Issue by KaustuvDas** [vlocityinc/vlocity_build#90]
Hi,
A quick help on below issue will be greatly appreciated.
I am trying to deploy a calculation matrix which contains around 77000 records using latest Vlocity Build and Node Js Command.
**Node JS version : 8.11
Vlocity Build : 1.6.2**

I exported the calculation matrix from source org using below command.
vlocity -propertyfile build_source.properties -job project.yaml packExport

And I am using below command to deploy the same calculation matrix to Target Org:
vlocity -propertyfile build_iat.properties -job project.yaml packDeploy

**ERROR Snippet attached below:**
![calculation marix error snippet](https://user-images.githubusercontent.com/42804518/44785068-30a33a00-ab7f-11e8-9dc8-2ee8d3fb33d9.PNG)

**Project.yaml Snippet :** 

projectPath: ./packExport
expansionPath: .
manifest:
- CalculationMatrix/ZPC Auto Vehicle Database
activate : true
compileOnBuild : true
maxDepth : 1
continueAfterError: true
defaultMaxParallel: 20
exportPacksMaxSize: 20
useAllRelationships: false
supportForceDeploy: true

**Deploy error:**
CalculationMatrix/ZPC Auto Vehicle Database -- DataPack >> ZPC Auto Vehicle Database -- Error Message -- vlocity_ins:Too many DML rows: 10001

**Comment by rutlabaga** [comment]
The issue here is happening when the DataPack tried to delete the older existing Matrix rows. A quick fix to this would be to manually delete the existing Matrix Version through the UI before upload in the target org. 

I will look into a more long term fix. 

If you need any further specific help please file a support ticket with Vlocity, just to move the conversation into a better channel. 

Thanks

**Comment by KaustuvDas** [comment]
Thanks!!

can we somewhere increase the DML limit beyond 10000 somewhere? Is there any significant impact by doing so?

**Comment by rutlabaga** [comment]
Unfortunately this one is a little uncommon, so not caught before. Usually the DataPacks would have switched to Async mode because of the size of this Matrix and the DML limits would be higher, but for some reason it is not hitting apex cpu limits and is instead getting to the the step where is cleans up stale records which in this case is >10000. 

I believe this can be fixed in the Build tool by deleting the version automatically before deploy, just like I had you do, or possibly forcing it to switch to Async Apex. Glad it worked and I will try to get the actual solution into the project soon.

Thanks for following up!
